Update ucp_prototype.yml

diff --git a/.github/workflows/ucp_prototype.yml b/.github/workflows/ucp_prototype.yml
--- a/.github/workflows/ucp_prototype.yml
+++ b/.github/workflows/ucp_prototype.yml
@@ -7,12 +7,24 @@ on:
 jobs:
   correctness-test:
     runs-on: ubuntu-latest
+    permissions:
+      contents: read
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
-      - name: Correctness test
-        uses: eliasmadere/UCPTest@main
+      - name: Set up script
+        uses: actions/setup-go@v5
         with:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          go-version: '1.22'
+      - name: Correctness test
+        id: grader
+        working-directory: ./correctness-test
+        env:
           GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
-          exclude: "yarn.lock,dist/**"
+        run: |
+          go run main.go
+      - name: Grade result
+        if: ${{ failure() && steps.grader.outcome == 'failure' }}
+        run: |
+          echo "Homework grading failed. Please check the 'Correctness test' step for details."
+          exit 1
